"""
Django settings for firstsite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'journify-local-development-only')

# Google Gemini AI API Key for geocoding
GEMINI_API_KEY_1 = os.environ.get('GEMINI_API_KEY_1', '')
JOURNIFY_PUBLIC_BASE_URL = os.environ.get('JOURNIFY_PUBLIC_BASE_URL', '')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to on for local development; set DJANGO_DEBUG=False when deploying.
# With DEBUG off, runserver stops serving /static/, so run collectstatic and
# put a real static file server in front (see README).
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() not in ('0', 'false', 'no')
# Force reload for new templatetags

ALLOWED_HOSTS = [host.strip() for host in os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    '*,.ngrok-free.app,.ngrok-free.dev,127.0.0.1,localhost,10.0.2.2,0.0.0.0',
).split(',') if host.strip()]

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.onrender.com',
]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'home',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "firstsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'home', 'Templates'),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "debug": DEBUG,  # Disable template caching in DEBUG mode
        },
    },
]

WSGI_APPLICATION = "firstsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "vi"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# Target for `manage.py collectstatic`, required once DEBUG is off.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# OpenStreetMap Nominatim identification (update email to your real contact per usage policy)
NOMINATIM_USER_AGENT = 'CS252-Dalat-TripPlanner/1.0 (mailto:tripplanner@example.com)'
NOMINATIM_EMAIL = 'tripplanner@example.com'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table", 
    }
}

LOGIN_URL = 'welcome'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Khi nào muốn gửi thật bằng Gmail thì dùng cấu hình này (bỏ comment):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'email_cua_ban@gmail.com'
# EMAIL_HOST_PASSWORD = 'mat_khau_ung_dung_google' # Không phải mật khẩu đăng nhập, là App Password


# --- Logging -----------------------------------------------------------------
# The itinerary algorithm emits a detailed step-by-step trace (clustering, TSP routing,
# eatery placement). It is useful while debugging and pure noise otherwise, so it sits at
# DEBUG level and is silenced by default.
#
# Enable it for one run with:  JOURNIFY_LOG_LEVEL=DEBUG python manage.py runserver
ALGORITHM_LOG_LEVEL = os.environ.get('JOURNIFY_LOG_LEVEL', 'WARNING').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[%(levelname)s] %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Vietnamese place names appear in these messages, which is exactly why they must not
        # go through a bare print() to a stdout that may not be UTF-8.
        'home.algorithm': {
            'handlers': ['console'],
            'level': ALGORITHM_LOG_LEVEL,
            'propagate': False,
        },
    },
}
