services:
  - type: web
    name: journify-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn firstsite.wsgi:application"
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_DEBUG
        value: "True"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY_1
        sync: false