# Generated by Django 5.2.7 on 2025-11-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eatery_price_per_person_eatery_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatery',
            name='price_per_person',
        ),
        migrations.AddField(
            model_name='eatery',
            name='price_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eatery',
            name='price_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
