# Generated by Django 5.2.7 on 2025-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.TextField()),
                ('normalized_address', models.TextField(db_index=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_address'], name='home_geocod_normali_f154de_idx'), models.Index(fields=['street', 'ward'], name='home_geocod_street_983a18_idx')],
            },
        ),
    ]
