# Generated by Django 5.2.7 on 2025-11-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_geocodedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodedlocation',
            name='place_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
