# Generated by Django 5.2.7 on 2025-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_profile_phone_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
