# Generated by Django 5.2.7 on 2025-11-25 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mood', models.CharField(db_index=True, max_length=80)),
                ('trip_days', models.PositiveSmallIntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('poi_count', models.PositiveSmallIntegerField(default=0)),
                ('eatery_count', models.PositiveSmallIntegerField(default=0)),
                ('start_address', models.CharField(blank=True, max_length=255)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lon', models.FloatField(blank=True, null=True)),
                ('start_fallback_used', models.BooleanField(default=False)),
                ('trip_setup', models.JSONField(blank=True, default=dict)),
                ('planner_step3', models.JSONField(blank=True, default=dict)),
                ('planner_itinerary', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('adopted_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_feedback', to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='home.shareditinerary')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('itinerary', 'user')},
            },
        ),
    ]
