# Generated by GitHub Copilot on 2025-11-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shareditinerary_itineraryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatery',
            name='image_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='image_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
