# Generated by Django 5.2.7 on 2025-12-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_poi_image_code_eatery_image_code'),
        ('home', '0011_shared_by_metadata'),
    ]

    operations = [
    ]
