# Generated by Django 5.2.7 on 2025-12-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_20251202_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
