# Generated by Django 5.2.8 on 2025-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_poi_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatery',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eatery',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eatery',
            name='time_tags_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='highlight_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='tags_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
