# Generated by Django 5.2.7 on 2025-12-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_itineraryresumetoken'),
        ('home', '0014_eatery_address_en_eatery_name_en_eatery_time_tags_en_and_more'),
    ]

    operations = [
    ]
