# Generated by Django 5.2.7 on 2026-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20251209_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('POI', 'Attraction'), ('EATERY', 'Eatery')], db_index=True, max_length=16)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('target_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CLOSED', 'Permanently closed'), ('TEMPORARILY_CLOSED', 'Temporarily closed'), ('WRONG_PRICE', 'Incorrect price'), ('WRONG_HOURS', 'Incorrect opening hours'), ('WRONG_ADDRESS', 'Incorrect address or location'), ('BROKEN_REVIEW', 'Broken review link'), ('WRONG_IMAGE', 'Incorrect image'), ('DUPLICATE', 'Duplicate place'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('description', models.TextField()),
                ('current_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', max_length=16)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='home_placer_target__5fd988_idx'), models.Index(fields=['status', 'created_at'], name='home_placer_status_906e40_idx')],
            },
        ),
    ]
